#! /bin/sh
if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    ...
elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    ...
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
fi
white="\e[0;37m"
greenbold="\e[1;32m"
green="\e[0;32m"
blue="\e[0;34m"
bluebold="\e[1;34m"
redbold="\e[1;31m"
phymem=$(free -m | grep -oP '\d+' | head -n 1)
freemem=$(free -m | grep -oP '\d+' | head -2 | tail -1)
Arch=$(hostnamectl | grep "Arch" | tail -n 1 | cut -b 19-) # Get The ARCH
Kernel=$(uname -r) # Get The Kernel Version
Host=$(hostname)
Sh=$(echo $SHELL | cut -b 6-)
Cpumodel=$(cat /proc/cpuinfo | grep "model name" | tail -n 1 | cut -b 14-)
Uptime=$(uptime -p | cut -b 4-)

color=$(cat /var/.vfetch/vfetch-config | tail -n 1 | cut -b 14-)
res=$(xdpyinfo | awk '/dimensions:/ { print $2 }')
printf $color
figlet $OS
printf "${greenbold}Host Name  ${white}: ${bluebold}$Host\n"
printf "${greenbold}OS         ${white}: ${bluebold}$OS $VER\n"
printf "${greenbold}Kernel     ${white}: ${bluebold}$Kernel\n"
printf "${greenbold}ARCH       ${white}: ${bluebold}$Arch\n"
printf "${greenbold}Shell      ${white}: ${bluebold}$Sh\n"
printf "${greenbold}Memory     ${white}: ${bluebold}Free ${white}: ${bluebold}$freemem Total ${white}: ${bluebold}$phymem MiB\n"
printf "${greenbold}Uptime     ${white}: ${bluebold}$Uptime\n"
printf "${greenbold}Resolution ${white}: ${bluebold}$res\n"
printf "${greenbold}CPU        ${white}: ${bluebold}$Cpumodel\n"

